### PR TITLE
Add @impl GenServer above GenServer callbacks

### PR DESCRIPTION
**Pull request by eoinkelly**
This change stops batch_please from generating compiler warnings in the
project which includes it.

### CODE REVIEW

**Comment by andyleclair** [comment]
I thought the correct syntax was `@impl true` based on the docs here https://hexdocs.pm/elixir/GenServer.html

**Comment by eoinkelly** [comment]
@andyleclair You can use either `@impl true` to signal that the function is implementing a behaviour or `@impl NameOfModuleWhichDefinesTheBehaviour` to be more explicit about which behaviour the function implements - see https://elixir-lang.org/blog/2017/07/25/elixir-v1-5-0-released/ (the @impl section about half way down). I went for the more explicit version but  I'm happy to change to `@impl true` if that is more palatable to the maintainers.

**Comment by andyleclair** [comment]
No, that is fine, it's just news to me!

This looks good, but I think @gamache has the keys to actually push a release to Hex so I'll bug him to do that. Thanks for the PR!

**Review by andyleclair — APPROVED** [review]

**Comment by gamache** [comment]
This looks great, thanks Eoin!

**Pull request merged**
